# Generated by Django 5.0.6 on 2024-06-27 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("location", models.CharField(max_length=200)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("online", "Online Meeting"),
                            ("gather", "Gather"),
                            ("field", "Field Event"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "attendees",
                    models.ManyToManyField(
                        related_name="events_attending", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_organized",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
