# Generated by Django 5.0.6 on 2024-06-17 21:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("278776ff-0205-49c9-bf25-2d7a5617390c"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="post-")),
                ("caption", models.TextField()),
                ("challenge", models.TextField()),
                ("short_discription", models.TextField()),
                ("full_discription", models.TextField()),
                ("no_of_likes", models.IntegerField(default=0)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Wildlife Conservation", "Wildlife Conservation"),
                            (
                                "Environmental Conservation",
                                "Environmental Conservation",
                            ),
                            ("Sustainable Development", "Sustainable Development"),
                            ("Community Engagement", "Community Engagement"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
