# Generated by Django 5.0.6 on 2024-06-17 21:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0002_story"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="profiling",
            new_name="profileing",
        ),
        migrations.AlterField(
            model_name="story",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a5a72051-240b-48c5-a69f-43605445103c"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
