# Generated by Django 5.0.6 on 2024-06-17 22:56

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0003_rename_profiling_profile_profileing_alter_story_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="story",
            old_name="full_discription",
            new_name="full_description",
        ),
        migrations.RenameField(
            model_name="story",
            old_name="short_discription",
            new_name="short_description",
        ),
        migrations.AddField(
            model_name="story",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="story",
            name="google_map_link",
            field=models.URLField(default="https://maps.google.com"),
        ),
        migrations.AddField(
            model_name="story",
            name="location",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="story",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("7915a56c-40c0-46cd-8210-f73bb34c6c85"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
