# Generated by Django 5.0.6 on 2024-06-19 18:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0005_likepost_alter_story_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="LikeStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.CharField(max_length=500)),
                ("username", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="LikePost",
        ),
        migrations.AlterField(
            model_name="story",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("669f5355-f539-4dcd-97fe-8046c703bb01"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
