# Generated by Django 5.0.6 on 2024-06-19 19:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0006_likestory_delete_likepost_alter_story_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("3be5861e-d8d8-45e8-998d-f32a117c82bb"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
