# Generated by Django 5.0.6 on 2024-06-19 22:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0007_alter_story_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="profileing",
            new_name="profileimg",
        ),
        migrations.AlterField(
            model_name="story",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("32e9ccbe-6c84-4cc3-9733-3b30bad68d46"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
