# Generated by Django 5.0.6 on 2024-06-20 01:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0008_rename_profileing_profile_profileimg_alter_story_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1d55af7d-1b54-4c7b-9ca1-a1d7046803a9"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
