# Generated by Django 5.0.6 on 2024-06-20 01:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0009_alter_story_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("fba63760-4ade-404c-a03f-e4433e51d38c"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
