# Generated by Django 5.0.6 on 2024-06-20 02:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0011_alter_story_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d53e8a05-44e7-4af4-b27f-6bf5bcd297ed"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
