# Generated by Django 5.0.6 on 2024-06-20 02:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0012_alter_story_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("cc619855-d50c-42d0-81db-b89350ace357"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
