# Generated by Django 5.0.6 on 2024-06-24 01:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0016_alter_story_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c7549f1f-c47d-417f-8e35-2912a136a783"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
