# Generated by Django 5.0.6 on 2024-06-24 01:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0017_alter_story_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followers",
            name="user",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="story",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("7d66aa73-90ba-4437-b32f-c38b5f507b72"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
