# Generated by Django 5.1b1 on 2024-07-16 14:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0019_remove_followers_created_at_alter_story_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.UUIDField(default=uuid.UUID('efc7ef98-fb49-489c-8c89-809e2331c48d'), primary_key=True, serialize=False),
        ),
    ]
