# Generated by Django 5.1b1 on 2024-07-16 21:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0020_alter_story_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b47e23f2-3525-4ce1-96c8-f2782d519a59'), primary_key=True, serialize=False),
        ),
    ]
