# Generated by Django 5.1b1 on 2024-07-19 17:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0021_alter_story_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9cb0219c-70cc-45c0-88cb-e02d948f0294'), primary_key=True, serialize=False),
        ),
    ]
