# Generated by Django 5.1b1 on 2024-07-19 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0022_alter_story_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.UUIDField(default=uuid.UUID('55484cc5-840d-4093-849b-bf6602d5fc3d'), primary_key=True, serialize=False),
        ),
    ]
