# Generated by Django 5.1b1 on 2024-07-19 18:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0025_alter_story_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ca06601-a1c4-464e-8669-399ba370f7b4'), primary_key=True, serialize=False),
        ),
    ]
